config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root 'projects#index', as: :authenticated_root
  end

  resources :projects do
    resources :notes, except: :show
    resources :tasks, except: :index do
      member do
        patch :toggle
      end
    end
    member do
      patch :complete
    end
  end

  namespace :api do
    resources :projects, only: %i[index show create]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  
  validates :name, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project
  before_action :project_owner?
  before_action :set_task, only: %i[ show edit update destroy toggle ]

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = @project.tasks.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = @project.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @project, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: [@task.project, @task] }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @project, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: [@task.project, @task] }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy!

    respond_to do |format|
      format.html { redirect_to @project, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def toggle
    @task.update(completed: !@task.completed)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:name, :completed, :project_id)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_completed.html.erb
<%= turbo_frame_tag task do %>
  <%= form_with model: task, url: [:toggle, task.project, task], html: { data: { controller: "task" } } do |f| %>
    <label id="<%= dom_id(task) %>" class="<%= task.completed? ? 'completed' : '' %>">
      <%= f.check_box :completed, { data: { action: "change->task#submit" } } %>
      <%= task.name %>
    </label>
  <% end %>
<% end %>

app/views/tasks/_form.html.erb
<%= form_with(model: [task.project, task]) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.check_box :completed %>
    <%= form.label :completed, class: "form-label" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
    <%= link_to "Cancel", task.project, class: "btn btn-light", data: { turbo_method: :get, turbo_confirm: "Are you sure?" } %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<tr class="task">
  <td>
    <%= render "tasks/completed", task: task %>
  </td>
  <td class="task-actions">
    <%= link_to edit_project_task_path(task.project, task),
                class: "btn btn-sm btn-light" do %>
      <span class="bi bi-pencil-fill" aria-hidden="true"></span>
      Edit
    <% end %>
    <%= button_to [task.project, task],
                  method: :delete,
                  data: { turbo_confirm: 'Are you sure?' },
                  class: "btn btn-light btn-sm",
                  form_class: "form-inline" do %>
      <span class="bi bi-trash" aria-hidden="true"></span>
      Delete
    <% end %>
  </td>
</tr>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render "form", task: @task %>

app/views/tasks/toggle.turbo_stream.erb
<%= turbo_stream.replace @task do %>
  <%= render 'completed', task: @task %>
<% end %>